[main]
font=JetBrainsMono Nerd Font:size=12
prompt="λ "
terminal=kitty
width=35
horizontal-pad=25
vertical-pad=15
inner-pad=8
include=~/.config/fuzzel/themes/noctalia

[colors]
# # Background: #f0eedd (Full Opacity)
# background=f0eeddff
# # Foreground/Text: #000000
# text=000000ff
# # Match (Characters you typed): A subtle dark grey/blue
# match=45475aff
# # Selection Background: A slightly darker tan/grey to stand out from the cream
# selection=e1dfcaff
# # Selection Text: Keep it black
# selection-text=000000ff
# # Border: Black to match your foreground
# border=000000ff

[border]
width=2
radius=0

