# Add your additional Hyprland configurations here
#
# This is an additional key binding
# bind = $mainMod CTRL, up, workspace, empty
#
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

input {
		follow_mouse = 1
}

cursor {
		no_warps = 1
}

# qt5ct environment variable
env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland

general {
		gaps_out = 10
		gaps_in = 5
		allow_tearing = true
}

windowrule = match:class tf_linux64, immediate yes
windowrule = match:class yuzu, immediate yes
windowrule = match:class Terraria.bin.x86_64, immediate yes
windowrule = match:class ^(Better than Adventure!)$, immediate yes
windowrule = match:title ^(?i)(Open|Save|Preferences|Settings|Properties|File Upload|Choose File|Close).*$, float yes

# Float XDG Portal Dialogs
windowrule = match:class ^(xdg-desktop-portal-gtk)$, float yes
windowrule = match:class ^(xdg-desktop-portal-gtk)$, center yes
windowrule =  match:class ^(xdg-desktop-portal-gtk)$ , size 900 600# Optional: set default size

# Uncomment in case you have issues with screensharing
# exec-once = ~/.config/hypr/scripts/xdg.sh
